name: CSV_export

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  CSV_export:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
    - name: Dependabot Alert CSV Export
      uses: ShamKarthikS-Hexaware/dependabot-alert-export@v1.0
      with:        
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          #org_name: 'ORG_NAME'
          #repo_name: 'REPO_NAME'
          csv_path: data/vulnerability.csv
    - name: Upload Vulnerability report
      uses: actions/upload-artifact@v3
      with:
           name: vulnerability_report
           path: data/vulnerability.csv     
